<?= $this->broker('doctype') ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <?php $this->broker('headTitle')->append('WELCOME TO SITE 1'); //@TODO: Why isn't this fluid? ?>
  <?= $this->broker('headTitle') ?>
  <?= $this->broker('headLink') ?>
</head>
<body>
<div id="header">
    <b>YOU ARE ON SITE 1</b>
</div>
<?= $this->render($this->vars('content_script'), new \Zend\View\Variables($this->vars('content'))); ?>
</body>
</html>
