<?php echo $this->doctype() ?>

<html lang="en">
  <head>
    <meta charset="utf-8">
    <?php echo $this->headTitle() ?>

    <?php echo $this->headMeta() ?>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <?php echo $this->placeholder('html5js') ?>

    <![endif]-->

    <?php echo $this->headScript() ?>

    <!-- Le styles -->
    <?php echo $this->headLink() ?>
    
    <style type="text/css">
      body {
        padding-top: 60px;
      }
      #captcha-element pre {
        clear: left;
        line-height: 15px;
        width: 360px;
      }
    </style>

    <!-- Le fav and touch icons -->
    <?php echo $this->placeholder('favicon') ?>

  </head>

  <body>

    <div class="topbar">
      <div class="fill">
        <div class="container">
          <a class="brand" href="<?php echo $this->url('home') ?>">ZF2 Sandbox</a>

          <ul class="nav">
            <li class="active"><a href="<?php echo $this->url('home') ?>">Home</a></li>
            <li><a href="<?php echo $this->url('mwopguestbook') ?>">Guestbook</a></li>
            <li><a href="<?php echo $this->url('edpuser/login') ?>">User</a></li>
          </ul>
          <?php if ($this->edpUserIdentity()): ?>
              <ul class="nav secondary-nav">
                <li><?php echo $this->gravatar($this->edpUserIdentity()->getEmail(), array('img_size' => 25), array('style' => 'padding-top: 8px;')) ?></li>
                <li><a href="<?php echo $this->url('edpuser') ?>"><?php echo $this->edpUserIdentity()->getDisplayName() ?></a></li>
                <li><a href="<?php echo $this->url('edpuser/logout') ?>">Sign Out</a></li>
              </ul>
          <?php else: ?>
              <form action="<?php echo $this->url('edpuser/login') ?>" method="post" class="pull-right">
                <input name="identity" class="input-small" type="text" placeholder="Username">
                <input name="credential" class="input-small" type="password" placeholder="Password">
                <?php echo $this->formCsrf('csrf') ?>
                <button class="btn" type="submit">Sign in</button>
              </form>
          <?php endif; ?>
        </div>
      </div>

    </div>

    <div class="container">
      <?php echo $this->raw('content'); ?>

      <footer>
        <p>Built by <a href="http://blog.evan.pro/">Evan Coury</a>.</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>
