<?= $this->broker('doctype') ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <?php $this->broker('headTitle')->append('ZF2 Sandbox'); //@TODO: Why isn't this fluid? ?>
  <?= $this->broker('headTitle') ?>
  <?= $this->broker('headLink') ?>
</head>
<body>
<div id="header">
    <b>My ZF2 Sandbox</b>
</div>
<?= $this->render($this->vars('content_script'), $this->vars('content')); ?>
</body>
</html>
