<?= $this->broker('doctype') ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <?= $this->broker('headTitle')->direct('Sorry!'); //@TODO: Why isn't this fluid? ?>
  <?= $this->broker('headLink') ?>
</head>
<body>
<div id="header">
    <b>The website you are looking for is not hosted on this server.</b>
</div>
<?= $this->render($this->vars('content_script'),  new \Zend\View\Variables($this->vars('content'))); ?>
</body>
</html>
